// Copyright 2023 The Flutter Authors. All rights reserved.
// Author: ＸＸＸ

/// getClassScheduleEx ................
///
/// Introduction: ................
///
///  * ................
///  * .......
///
///
